# -*- coding: utf-8 -*-
"""50-startups-MLR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/naveenkumar-4/309fbc4814cedfa3a3a1de80943e8d63/50-startups-mlr.ipynb
"""

import pandas as pd
data = pd.read_csv('50_Startups_MLR.csv')

data

# independent Variables - X

X = data.iloc[:,0:-1].values

X

# Dependent Variables - Y

Y = data.iloc[:,-1].values

Y

from sklearn.impute import SimpleImputer
import numpy as np
imputer = SimpleImputer(missing_values = np.nan,strategy = 'mean')
imputer.fit(X[:,0:3])
X[:,0:3]=imputer.transform(X[:,0:3])

X

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder ='passthrough')
X=ct.fit_transform(X)

X

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

X_train

X_test

Y_train

Y_test